#!/bin/sh
#Install dependencies
sudo apt update
sudo apt install -y python python3-pip net-tools tree python3-flask

#Gather Instance Data
UI_IP=$(curl https://ipinfo.io/ip)
UI_PORT="8080"
UI_UUID="${deployment_uuid}"
UI_OWNER="${deployment_owner}"
JSON="{\"ip\":\"$UI_IP\",\"port\":\"$UI_PORT\",\"owner\":\"$UI_OWNER\",\"uuid\":\"$UI_UUID\"}"

#Write LDS Instance Data
echo "owner=${deployment_owner}" > /home/ubuntu/lds_settings
echo "uuid=${deployment_uuid}" >> /home/ubuntu/lds_settings

#Notify Torq
curl -d "$JSON" -H 'Content-Type: application/json' https://hooks.torq.io/v1/webhooks/22f129f2-d7dc-474e-aabe-da2d1d9893bd

#Run App
cd /home/ubuntu
git clone https://github.com/joe-at-torq/TorqLDS-UI.git
cd TorqLDS-UI/reg-form/
nohup ./StartPublic.sh &

