#!/bin/sh
#Install dependencies
sudo apt update
sudo apt install -y python python3-pip net-tools tree python3-flask

#Gather Instance Data
UI_IP=$(curl https://ipinfo.io/ip)
UI_PORT="8080"
UI_UUID="${deployment_uuid}"
UI_OWNER="${deployment_owner}"
UI_WEBHOOK="${deployment_webhook}"
JSON="{\"notification_type\":\"new_ui_deployed\",\"ip\":\"$UI_IP\",\"port\":\"$UI_PORT\",\"deployment_owner\":\"$UI_OWNER\",\"uuid\":\"$UI_UUID\"}"

#Notify Torq
curl -d "$JSON" -H 'Content-Type: application/json' $UI_WEBHOOK

#Run App
cd /home/ubuntu
git clone https://github.com/joe-at-torq/TorqLDS-UI.git

#Write LDS Instance Data
echo "{\"owner\":\"${deployment_owner}\",\"uuid\":\"${deployment_uuid}\",\"webhook\":\"${deployment_webhook}\"}" > /home/ubuntu/TorqLDS-UI/reg-form/lds_settings.json

#Generate the SSL Certificate and start the UI
cd TorqLDS-UI/reg-form/
openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365 -subj "/C=US/ST=Texas/L=Dallas/O=torq/OU=training/CN=*.torq.training"
nohup ./StartPublic.sh &

